### ISSUE TITLE
Tutorial: basic settings alpharaw

### ISSUE THREAD

**Issue by jalew188** [MannLabs/alpharaw#68]
The tutorial notebook of basic settings in alpharaw.

**Comment by JuliaS92** [comment]
Could you maybe include a short explanation of how to configure proteases by regex? The regex are non-trivial but it's something wetlab people might want to do. Something like a template for N vs C-terminal cleavage and how to incorporate exclusion patterns would suffice.

**Comment by jalew188** [comment]
> Could you maybe include a short explanation of how to configure proteases by regex? The regex are non-trivial but it's something wetlab people might want to do. Something like a template for N vs C-terminal cleavage and how to incorporate exclusion patterns would suffice.

Yes, MB move this to alphabase tutorial?
